const frPosts = [
    {
        id: 1,
        frName: 'Nguyễn Đạt',
        tagged: 'Hoang Huynh',
        title: 'Đà Nẵng về đem cùng thằng em',
        image: '/img/post1.jpeg',
        frAvatar: '/img/avtDat.jpg',
        tag: true,
        time: '1 giờ',
        numbLike: 7824,
        numbCmt: 0,
        numbShare: 321,
    },

    {
        id: 2,
        frName: 'Nguyễn Đạt',
        tagged: 'Hoang Huynh',
        title: 'Offline đeeeeeeeeeee anh em ơi',
        image: '/img/post2.jpeg',
        frAvatar: '/img/avtDat.jpg',
        tag: true,
        time: '24 tháng 6 lúc 14:21',
        numbLike: 2014,
        numbCmt: 0,
        numbShare: 936,
    },

    {
        id: 3,
        frName: 'Dog Cool Detailing',
        tagged: 'Hoang Huynh',
        title: '=)) Thằng em đem xem qua bảo dưỡng mà dìm ác quá nha.',
        image: '/img/detail.jpg',
        frAvatar: '/img/pic2.jpg',
        tag: true,
        time: '5 giờ',
        numbLike: 6876,
        numbCmt: 0,
        numbShare: 620,
    },

    {
        id: 4,
        frName: 'Senyamiku',
        tagged: 'Hoang Huynh',
        title: 'Hình ảnh Hoàng chờ tui makeup để chuẩn bị đi chơi 😜 hơi lâu tý ^^',
        image: '/img/news.jpg',
        frAvatar: '/img/avtMiku.jpg',
        tag: true,
        time: '7 giờ',
        numbLike: 3836,
        numbCmt: 0,
        numbShare: 876,
    },

    {
        id: 5,
        frName: 'Senyamiku',
        title: 'Siuuuuuuuuuuuuu',
        frAvatar: '/img/pic7.jpg',
        tag: false,
        time: '9 giờ',
        numbLike: 3008,
        numbCmt: 0,
        numbShare: 747,
    },
    {
        id: 6,
        frName: 'Nguyen Quoc Cuong',
        title: 'Lần đầu cho e đi xa 😋',
        hastag: '#911GT3-992',
        image: '/img/postCuong1.jpg',
        frAvatar: '/img/avtCuong.jpg',
        tag: false,
        time: '18 tháng 6 lúc 09:54',
        numbLike: 6850,
        numbCmt: 0,
        numbShare: 959,
    },
    {
        id: 7,
        frName: 'Phạm Trần Nhật Minh',
        title: 'Dọn xe sạch sẽ để đi chơi nè 😜',
        hastag: '#phamtrannhatminh #minhnhua #nmfamily #passion #pagani #paganihuayra #hypercar',
        image: '/img/postMinh1.jpg',
        frAvatar: '/img/avtMinh.jpg',
        tag: false,
        time: '24 tháng 6 lúc 19:53',
        numbLike: 8720,
        numbCmt: 0,
        numbShare: 377,
    },

    {
        id: 8,
        frName: 'Nguyen Quoc Cuong',
        tagged: 'Hoang Huynh',
        title: 'Job kiếm thêm thu nhập ngày cuối tuần 😜',
        hastag: '#911GT3-992',
        image: '/img/postCuong2.jpg',
        frAvatar: '/img/avtCuong.jpg',
        tag: true,
        time: '26 tháng 3',
        numbLike: 3976,
        numbCmt: 0,
        numbShare: 684,
    },

    {
        id: 9,
        frName: 'Senyamiku',
        tagged: 'Hoang Huynh',
        title: 'Disney Disney Thượng Hải! 🏰🐤. Đi chơi với bạn Hoàng của tui ^^.',
        image: '/img/mikuPost1.jpg',
        frAvatar: '/img/avtMiku.jpg',
        tag: true,
        time: '11 giờ',
        numbLike: 1896,
        numbCmt: 0,
        numbShare: 928,
    },
]

export { frPosts }
